//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.10 at 04:54:33 PM MEZ 
//


package net.sf.otrcutmp4.model.xml.otr;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://otrcutmp4.sf.net/otr}download" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://otrcutmp4.sf.net/otr}recording" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "download",
    "recording"
})
@XmlRootElement(name = "linklist")
public class Linklist
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected List<Download> download;
    @XmlElement(required = true)
    protected List<Recording> recording;

    /**
     * Gets the value of the download property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the download property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDownload().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Download }
     * 
     * 
     */
    public List<Download> getDownload() {
        if (download == null) {
            download = new ArrayList<Download>();
        }
        return this.download;
    }

    public boolean isSetDownload() {
        return ((this.download!= null)&&(!this.download.isEmpty()));
    }

    public void unsetDownload() {
        this.download = null;
    }

    /**
     * Gets the value of the recording property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recording property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecording().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Recording }
     * 
     * 
     */
    public List<Recording> getRecording() {
        if (recording == null) {
            recording = new ArrayList<Recording>();
        }
        return this.recording;
    }

    public boolean isSetRecording() {
        return ((this.recording!= null)&&(!this.recording.isEmpty()));
    }

    public void unsetRecording() {
        this.recording = null;
    }

}
