//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.16 at 05:25:26 PM MEZ 
//


package net.sf.otrcutmp4.model.xml.cut;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import net.sf.otrcutmp4.model.xml.otr.OtrId;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://otrcutmp4.sf.net/otr}otrId"/>
 *         &lt;element ref="{http://otrcutmp4.sf.net/cut}fileName"/>
 *         &lt;element ref="{http://otrcutmp4.sf.net/cut}cutList"/>
 *         &lt;element ref="{http://otrcutmp4.sf.net/cut}cutLists"/>
 *         &lt;element ref="{http://otrcutmp4.sf.net/cut}cutListsAvailable"/>
 *         &lt;element ref="{http://otrcutmp4.sf.net/cut}cutListsSelected"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "otrId",
    "fileName",
    "cutList",
    "cutLists",
    "cutListsAvailable",
    "cutListsSelected"
})
@XmlRootElement(name = "videoFile")
public class VideoFile
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(namespace = "http://otrcutmp4.sf.net/otr", required = true)
    protected OtrId otrId;
    @XmlElement(required = true)
    protected FileName fileName;
    @XmlElement(required = true)
    protected CutList cutList;
    @XmlElement(required = true)
    protected CutLists cutLists;
    @XmlElement(required = true)
    protected CutListsAvailable cutListsAvailable;
    @XmlElement(required = true)
    protected CutListsSelected cutListsSelected;

    /**
     * Gets the value of the otrId property.
     * 
     * @return
     *     possible object is
     *     {@link OtrId }
     *     
     */
    public OtrId getOtrId() {
        return otrId;
    }

    /**
     * Sets the value of the otrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtrId }
     *     
     */
    public void setOtrId(OtrId value) {
        this.otrId = value;
    }

    public boolean isSetOtrId() {
        return (this.otrId!= null);
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link FileName }
     *     
     */
    public FileName getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileName }
     *     
     */
    public void setFileName(FileName value) {
        this.fileName = value;
    }

    public boolean isSetFileName() {
        return (this.fileName!= null);
    }

    /**
     * Gets the value of the cutList property.
     * 
     * @return
     *     possible object is
     *     {@link CutList }
     *     
     */
    public CutList getCutList() {
        return cutList;
    }

    /**
     * Sets the value of the cutList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CutList }
     *     
     */
    public void setCutList(CutList value) {
        this.cutList = value;
    }

    public boolean isSetCutList() {
        return (this.cutList!= null);
    }

    /**
     * Gets the value of the cutLists property.
     * 
     * @return
     *     possible object is
     *     {@link CutLists }
     *     
     */
    public CutLists getCutLists() {
        return cutLists;
    }

    /**
     * Sets the value of the cutLists property.
     * 
     * @param value
     *     allowed object is
     *     {@link CutLists }
     *     
     */
    public void setCutLists(CutLists value) {
        this.cutLists = value;
    }

    public boolean isSetCutLists() {
        return (this.cutLists!= null);
    }

    /**
     * Gets the value of the cutListsAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link CutListsAvailable }
     *     
     */
    public CutListsAvailable getCutListsAvailable() {
        return cutListsAvailable;
    }

    /**
     * Sets the value of the cutListsAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link CutListsAvailable }
     *     
     */
    public void setCutListsAvailable(CutListsAvailable value) {
        this.cutListsAvailable = value;
    }

    public boolean isSetCutListsAvailable() {
        return (this.cutListsAvailable!= null);
    }

    /**
     * Gets the value of the cutListsSelected property.
     * 
     * @return
     *     possible object is
     *     {@link CutListsSelected }
     *     
     */
    public CutListsSelected getCutListsSelected() {
        return cutListsSelected;
    }

    /**
     * Sets the value of the cutListsSelected property.
     * 
     * @param value
     *     allowed object is
     *     {@link CutListsSelected }
     *     
     */
    public void setCutListsSelected(CutListsSelected value) {
        this.cutListsSelected = value;
    }

    public boolean isSetCutListsSelected() {
        return (this.cutListsSelected!= null);
    }

}
